services:
  postgres-db2:
    container_name: postgress2  
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gs
    ports:
      - "5433:5432" # Docker konteyner ichida PostgreSQL 5432 portda ishlaydi
    volumes:
      - db_data:/var/lib/postgresql/data # Ma'lumotlarni saqlash uchun volume
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
    networks:
      - app_network
    restart: always

  redis2:
    image: redis
    container_name: redis2
    ports:
      - "6380:6379" # Redis konteyner ichida 6379 portda ishlaydi
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
    networks:
      - app_network
    restart: always

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db2:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:1234@postgress2:5432/gs?sslmode=disable", "up"]  
    networks:
      - app_network

  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - GIN_MODE=release
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=photos
    depends_on:
      postgres-db2:
        condition: service_healthy
      redis2:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: always
    networks:
      - app_network
  
  minio:
    restart: always
    container_name: minio
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://54.93.213.231:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network

volumes:
  db_data: # Bu volume PostgreSQL ma'lumotlarini saqlash uchun ishlatiladi
  minio_data:

networks:
  app_network:
    driver: bridge