services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - GIN_MODE=release
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db:
    driver: local

networks:
  app_network:
    driver: bridge