services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgress:5432/postgres?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db:
    driver: local

networks:
  app_network:
    driver: bridge
    external: true