version: '3.8'

services:
  migrate:
    image: migrate/migrate
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:1234@postgres-db:5432/asror_gps?sslmode=disable", "up"]  
    networks:
      - app_network

  app:
    build: .
    container_name: asror_gps
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:1234@postgres-db:5432/asror_gps?sslmode=disable
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - app_network
    restart: always
