// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/upload_image": {
            "post": {
                "description": "Bu endpoint foydalanuvchiga rasm (.jpg, .jpeg, .png) yoki video (.mp4) fayllarni yuklash imkonini beradi. Fayl MinIO serveriga saqlanadi va URL qaytariladi.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Faylni yuklash",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Yuklanadigan fayl (faqat .jpg, .jpeg, .png yoki .mp4 formatlari qabul qilinadi)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Fayl muvaffaqiyatli yuklandi\" Example({\"file_url\": \"http://minio:9000/images/abc123.jpg\"})",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Noto'g'ri so'rov yoki fayl turi\" Example({\"error\": \"Yaroqsiz fayl turi\"})",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Server xatosi\" Example({\"error\": \"MinIO bilan bog'lanishda xatolik: ...\"})",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Google_docs_user API",
	Description:      "This is an API for e-commerce platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
