basePath: /
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: This is an API for e-commerce platform.
  termsOfService: http://swagger.io/terms/
  title: Google_docs_user API
  version: "1.0"
paths:
  /auth/products/media/{email}:
    post:
      consumes:
      - multipart/form-data
      description: Api for upload a new photo
      parameters:
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      - description: createUserModel
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload Photo
      tags:
      - auth_media
swagger: "2.0"
