basePath: /
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: This is an API for e-commerce platform.
  termsOfService: http://swagger.io/terms/
  title: Google_docs_user API
  version: "1.0"
paths:
  /upload_image:
    post:
      consumes:
      - multipart/form-data
      description: Bu endpoint foydalanuvchiga rasm (.jpg, .jpeg, .png) yoki video
        (.mp4) fayllarni yuklash imkonini beradi. Fayl MinIO serveriga saqlanadi va
        URL qaytariladi.
      parameters:
      - description: Yuklanadigan fayl (faqat .jpg, .jpeg, .png yoki .mp4 formatlari
          qabul qilinadi)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 'Fayl muvaffaqiyatli yuklandi" Example({"file_url": "http://minio:9000/images/abc123.jpg"})'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'Noto''g''ri so''rov yoki fayl turi" Example({"error": "Yaroqsiz
            fayl turi"})'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Server xatosi" Example({"error": "MinIO bilan bog''lanishda
            xatolik: ..."})'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Faylni yuklash
      tags:
      - Media
swagger: "2.0"
